// Generated by gencpp from file dofbot_pro_info/ActionData.msg
// DO NOT EDIT!


#ifndef DOFBOT_PRO_INFO_MESSAGE_ACTIONDATA_H
#define DOFBOT_PRO_INFO_MESSAGE_ACTIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace dofbot_pro_info
{
template <class ContainerAllocator>
struct ActionData_
{
  typedef ActionData_<ContainerAllocator> Type;

  ActionData_()
    : values()
    , target_mask()  {
    }
  ActionData_(const ContainerAllocator& _alloc)
    : values(_alloc)
    , target_mask(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _values_type;
  _values_type values;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _target_mask_type;
  _target_mask_type target_mask;





  typedef boost::shared_ptr< ::dofbot_pro_info::ActionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dofbot_pro_info::ActionData_<ContainerAllocator> const> ConstPtr;

}; // struct ActionData_

typedef ::dofbot_pro_info::ActionData_<std::allocator<void> > ActionData;

typedef boost::shared_ptr< ::dofbot_pro_info::ActionData > ActionDataPtr;
typedef boost::shared_ptr< ::dofbot_pro_info::ActionData const> ActionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dofbot_pro_info::ActionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dofbot_pro_info::ActionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dofbot_pro_info::ActionData_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::ActionData_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values &&
    lhs.target_mask == rhs.target_mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dofbot_pro_info::ActionData_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::ActionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dofbot_pro_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::ActionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::ActionData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::ActionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cbfe2cf0aee067c2c9f1366a832d746";
  }

  static const char* value(const ::dofbot_pro_info::ActionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cbfe2cf0aee067cULL;
  static const uint64_t static_value2 = 0x2c9f1366a832d746ULL;
};

template<class ContainerAllocator>
struct DataType< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dofbot_pro_info/ActionData";
  }

  static const char* value(const ::dofbot_pro_info::ActionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] values\n"
"sensor_msgs/Image target_mask\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dofbot_pro_info::ActionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
      stream.next(m.target_mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dofbot_pro_info::ActionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dofbot_pro_info::ActionData_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
    s << indent << "target_mask: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.target_mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOFBOT_PRO_INFO_MESSAGE_ACTIONDATA_H
