// Generated by gencpp from file dofbot_pro_info/AprilTagInfo.msg
// DO NOT EDIT!


#ifndef DOFBOT_PRO_INFO_MESSAGE_APRILTAGINFO_H
#define DOFBOT_PRO_INFO_MESSAGE_APRILTAGINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dofbot_pro_info
{
template <class ContainerAllocator>
struct AprilTagInfo_
{
  typedef AprilTagInfo_<ContainerAllocator> Type;

  AprilTagInfo_()
    : id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  AprilTagInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> const> ConstPtr;

}; // struct AprilTagInfo_

typedef ::dofbot_pro_info::AprilTagInfo_<std::allocator<void> > AprilTagInfo;

typedef boost::shared_ptr< ::dofbot_pro_info::AprilTagInfo > AprilTagInfoPtr;
typedef boost::shared_ptr< ::dofbot_pro_info::AprilTagInfo const> AprilTagInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dofbot_pro_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d20216eb5e284a7b38d57a68c4a62b25";
  }

  static const char* value(const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd20216eb5e284a7bULL;
  static const uint64_t static_value2 = 0x38d57a68c4a62b25ULL;
};

template<class ContainerAllocator>
struct DataType< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dofbot_pro_info/AprilTagInfo";
  }

  static const char* value(const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AprilTagInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dofbot_pro_info::AprilTagInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOFBOT_PRO_INFO_MESSAGE_APRILTAGINFO_H
