// Generated by gencpp from file dofbot_pro_info/cur_joint.msg
// DO NOT EDIT!


#ifndef DOFBOT_PRO_INFO_MESSAGE_CUR_JOINT_H
#define DOFBOT_PRO_INFO_MESSAGE_CUR_JOINT_H

#include <ros/service_traits.h>


#include <dofbot_pro_info/cur_jointRequest.h>
#include <dofbot_pro_info/cur_jointResponse.h>


namespace dofbot_pro_info
{

struct cur_joint
{

typedef cur_jointRequest Request;
typedef cur_jointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cur_joint
} // namespace dofbot_pro_info


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dofbot_pro_info::cur_joint > {
  static const char* value()
  {
    return "7bf4e10c269e4b461f9707a22ed78be1";
  }

  static const char* value(const ::dofbot_pro_info::cur_joint&) { return value(); }
};

template<>
struct DataType< ::dofbot_pro_info::cur_joint > {
  static const char* value()
  {
    return "dofbot_pro_info/cur_joint";
  }

  static const char* value(const ::dofbot_pro_info::cur_joint&) { return value(); }
};


// service_traits::MD5Sum< ::dofbot_pro_info::cur_jointRequest> should match
// service_traits::MD5Sum< ::dofbot_pro_info::cur_joint >
template<>
struct MD5Sum< ::dofbot_pro_info::cur_jointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dofbot_pro_info::cur_joint >::value();
  }
  static const char* value(const ::dofbot_pro_info::cur_jointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dofbot_pro_info::cur_jointRequest> should match
// service_traits::DataType< ::dofbot_pro_info::cur_joint >
template<>
struct DataType< ::dofbot_pro_info::cur_jointRequest>
{
  static const char* value()
  {
    return DataType< ::dofbot_pro_info::cur_joint >::value();
  }
  static const char* value(const ::dofbot_pro_info::cur_jointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dofbot_pro_info::cur_jointResponse> should match
// service_traits::MD5Sum< ::dofbot_pro_info::cur_joint >
template<>
struct MD5Sum< ::dofbot_pro_info::cur_jointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dofbot_pro_info::cur_joint >::value();
  }
  static const char* value(const ::dofbot_pro_info::cur_jointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dofbot_pro_info::cur_jointResponse> should match
// service_traits::DataType< ::dofbot_pro_info::cur_joint >
template<>
struct DataType< ::dofbot_pro_info::cur_jointResponse>
{
  static const char* value()
  {
    return DataType< ::dofbot_pro_info::cur_joint >::value();
  }
  static const char* value(const ::dofbot_pro_info::cur_jointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOFBOT_PRO_INFO_MESSAGE_CUR_JOINT_H
