// Generated by gencpp from file dofbot_pro_info/joint_info.msg
// DO NOT EDIT!


#ifndef DOFBOT_PRO_INFO_MESSAGE_JOINT_INFO_H
#define DOFBOT_PRO_INFO_MESSAGE_JOINT_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dofbot_pro_info
{
template <class ContainerAllocator>
struct joint_info_
{
  typedef joint_info_<ContainerAllocator> Type;

  joint_info_()
    : name()
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
    }
  joint_info_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _joint1_type;
  _joint1_type joint1;

   typedef double _joint2_type;
  _joint2_type joint2;

   typedef double _joint3_type;
  _joint3_type joint3;

   typedef double _joint4_type;
  _joint4_type joint4;

   typedef double _joint5_type;
  _joint5_type joint5;

   typedef double _joint6_type;
  _joint6_type joint6;





  typedef boost::shared_ptr< ::dofbot_pro_info::joint_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dofbot_pro_info::joint_info_<ContainerAllocator> const> ConstPtr;

}; // struct joint_info_

typedef ::dofbot_pro_info::joint_info_<std::allocator<void> > joint_info;

typedef boost::shared_ptr< ::dofbot_pro_info::joint_info > joint_infoPtr;
typedef boost::shared_ptr< ::dofbot_pro_info::joint_info const> joint_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dofbot_pro_info::joint_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dofbot_pro_info::joint_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dofbot_pro_info::joint_info_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::joint_info_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.joint1 == rhs.joint1 &&
    lhs.joint2 == rhs.joint2 &&
    lhs.joint3 == rhs.joint3 &&
    lhs.joint4 == rhs.joint4 &&
    lhs.joint5 == rhs.joint5 &&
    lhs.joint6 == rhs.joint6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dofbot_pro_info::joint_info_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::joint_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dofbot_pro_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::joint_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::joint_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::joint_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e4c5975a569a0944e360fbd0ea6d70a";
  }

  static const char* value(const ::dofbot_pro_info::joint_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e4c5975a569a094ULL;
  static const uint64_t static_value2 = 0x4e360fbd0ea6d70aULL;
};

template<class ContainerAllocator>
struct DataType< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dofbot_pro_info/joint_info";
  }

  static const char* value(const ::dofbot_pro_info::joint_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  name\n"
"float64 joint1\n"
"float64 joint2\n"
"float64 joint3\n"
"float64 joint4\n"
"float64 joint5\n"
"float64 joint6\n"
;
  }

  static const char* value(const ::dofbot_pro_info::joint_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.joint5);
      stream.next(m.joint6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dofbot_pro_info::joint_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dofbot_pro_info::joint_info_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "joint1: ";
    Printer<double>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<double>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<double>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<double>::stream(s, indent + "  ", v.joint4);
    s << indent << "joint5: ";
    Printer<double>::stream(s, indent + "  ", v.joint5);
    s << indent << "joint6: ";
    Printer<double>::stream(s, indent + "  ", v.joint6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOFBOT_PRO_INFO_MESSAGE_JOINT_INFO_H
