// Generated by gencpp from file dofbot_pro_info/ShapeInfo.msg
// DO NOT EDIT!


#ifndef DOFBOT_PRO_INFO_MESSAGE_SHAPEINFO_H
#define DOFBOT_PRO_INFO_MESSAGE_SHAPEINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dofbot_pro_info
{
template <class ContainerAllocator>
struct ShapeInfo_
{
  typedef ShapeInfo_<ContainerAllocator> Type;

  ShapeInfo_()
    : value()  {
    }
  ShapeInfo_(const ContainerAllocator& _alloc)
    : value(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ShapeInfo_

typedef ::dofbot_pro_info::ShapeInfo_<std::allocator<void> > ShapeInfo;

typedef boost::shared_ptr< ::dofbot_pro_info::ShapeInfo > ShapeInfoPtr;
typedef boost::shared_ptr< ::dofbot_pro_info::ShapeInfo const> ShapeInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator2> & rhs)
{
  return lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dofbot_pro_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1becc0cb8362a822e3753aa6cf42cf70";
  }

  static const char* value(const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1becc0cb8362a822ULL;
  static const uint64_t static_value2 = 0xe3753aa6cf42cf70ULL;
};

template<class ContainerAllocator>
struct DataType< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dofbot_pro_info/ShapeInfo";
  }

  static const char* value(const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] value\n"
;
  }

  static const char* value(const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShapeInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dofbot_pro_info::ShapeInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dofbot_pro_info::ShapeInfo_<ContainerAllocator>& v)
  {
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOFBOT_PRO_INFO_MESSAGE_SHAPEINFO_H
