// Generated by gencpp from file dofbot_pro_info/WidthInfo.msg
// DO NOT EDIT!


#ifndef DOFBOT_PRO_INFO_MESSAGE_WIDTHINFO_H
#define DOFBOT_PRO_INFO_MESSAGE_WIDTHINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dofbot_pro_info
{
template <class ContainerAllocator>
struct WidthInfo_
{
  typedef WidthInfo_<ContainerAllocator> Type;

  WidthInfo_()
    : L_x(0.0)
    , L_y(0.0)
    , R_x(0.0)
    , R_y(0.0)  {
    }
  WidthInfo_(const ContainerAllocator& _alloc)
    : L_x(0.0)
    , L_y(0.0)
    , R_x(0.0)
    , R_y(0.0)  {
  (void)_alloc;
    }



   typedef float _L_x_type;
  _L_x_type L_x;

   typedef float _L_y_type;
  _L_y_type L_y;

   typedef float _R_x_type;
  _R_x_type R_x;

   typedef float _R_y_type;
  _R_y_type R_y;





  typedef boost::shared_ptr< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> const> ConstPtr;

}; // struct WidthInfo_

typedef ::dofbot_pro_info::WidthInfo_<std::allocator<void> > WidthInfo;

typedef boost::shared_ptr< ::dofbot_pro_info::WidthInfo > WidthInfoPtr;
typedef boost::shared_ptr< ::dofbot_pro_info::WidthInfo const> WidthInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dofbot_pro_info::WidthInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dofbot_pro_info::WidthInfo_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::WidthInfo_<ContainerAllocator2> & rhs)
{
  return lhs.L_x == rhs.L_x &&
    lhs.L_y == rhs.L_y &&
    lhs.R_x == rhs.R_x &&
    lhs.R_y == rhs.R_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dofbot_pro_info::WidthInfo_<ContainerAllocator1> & lhs, const ::dofbot_pro_info::WidthInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dofbot_pro_info

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de9e03608448f2f1799b1dfee66084ae";
  }

  static const char* value(const ::dofbot_pro_info::WidthInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde9e03608448f2f1ULL;
  static const uint64_t static_value2 = 0x799b1dfee66084aeULL;
};

template<class ContainerAllocator>
struct DataType< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dofbot_pro_info/WidthInfo";
  }

  static const char* value(const ::dofbot_pro_info::WidthInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 L_x\n"
"float32 L_y\n"
"float32 R_x\n"
"float32 R_y\n"
;
  }

  static const char* value(const ::dofbot_pro_info::WidthInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.L_x);
      stream.next(m.L_y);
      stream.next(m.R_x);
      stream.next(m.R_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WidthInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dofbot_pro_info::WidthInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dofbot_pro_info::WidthInfo_<ContainerAllocator>& v)
  {
    s << indent << "L_x: ";
    Printer<float>::stream(s, indent + "  ", v.L_x);
    s << indent << "L_y: ";
    Printer<float>::stream(s, indent + "  ", v.L_y);
    s << indent << "R_x: ";
    Printer<float>::stream(s, indent + "  ", v.R_x);
    s << indent << "R_y: ";
    Printer<float>::stream(s, indent + "  ", v.R_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOFBOT_PRO_INFO_MESSAGE_WIDTHINFO_H
