//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dofbot_pro_voice_ctrl package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dofbot_pro_voice_ctrl__COLORHSVCONFIG_H__
#define __dofbot_pro_voice_ctrl__COLORHSVCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dofbot_pro_voice_ctrl
{
  class ColorHSVConfigStatics;

  class ColorHSVConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(ColorHSVConfig &config, const ColorHSVConfig &max, const ColorHSVConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const ColorHSVConfig &config1, const ColorHSVConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, ColorHSVConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const ColorHSVConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ColorHSVConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const ColorHSVConfig &config) const = 0;
      virtual void getValue(const ColorHSVConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T ColorHSVConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T ColorHSVConfig::* field;

      virtual void clamp(ColorHSVConfig &config, const ColorHSVConfig &max, const ColorHSVConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const ColorHSVConfig &config1, const ColorHSVConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, ColorHSVConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const ColorHSVConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, ColorHSVConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const ColorHSVConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const ColorHSVConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, ColorHSVConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, ColorHSVConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<ColorHSVConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(ColorHSVConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("R_Hmin"==(*_i)->name){R_Hmin = boost::any_cast<int>(val);}
        if("R_Smin"==(*_i)->name){R_Smin = boost::any_cast<int>(val);}
        if("R_Vmin"==(*_i)->name){R_Vmin = boost::any_cast<int>(val);}
        if("R_Hmax"==(*_i)->name){R_Hmax = boost::any_cast<int>(val);}
        if("R_Smax"==(*_i)->name){R_Smax = boost::any_cast<int>(val);}
        if("R_Vmax"==(*_i)->name){R_Vmax = boost::any_cast<int>(val);}
        if("G_Hmin"==(*_i)->name){G_Hmin = boost::any_cast<int>(val);}
        if("G_Smin"==(*_i)->name){G_Smin = boost::any_cast<int>(val);}
        if("G_Vmin"==(*_i)->name){G_Vmin = boost::any_cast<int>(val);}
        if("G_Hmax"==(*_i)->name){G_Hmax = boost::any_cast<int>(val);}
        if("G_Smax"==(*_i)->name){G_Smax = boost::any_cast<int>(val);}
        if("G_Vmax"==(*_i)->name){G_Vmax = boost::any_cast<int>(val);}
        if("B_Hmin"==(*_i)->name){B_Hmin = boost::any_cast<int>(val);}
        if("B_Smin"==(*_i)->name){B_Smin = boost::any_cast<int>(val);}
        if("B_Vmin"==(*_i)->name){B_Vmin = boost::any_cast<int>(val);}
        if("B_Hmax"==(*_i)->name){B_Hmax = boost::any_cast<int>(val);}
        if("B_Smax"==(*_i)->name){B_Smax = boost::any_cast<int>(val);}
        if("B_Vmax"==(*_i)->name){B_Vmax = boost::any_cast<int>(val);}
        if("Y_Hmin"==(*_i)->name){Y_Hmin = boost::any_cast<int>(val);}
        if("Y_Smin"==(*_i)->name){Y_Smin = boost::any_cast<int>(val);}
        if("Y_Vmin"==(*_i)->name){Y_Vmin = boost::any_cast<int>(val);}
        if("Y_Hmax"==(*_i)->name){Y_Hmax = boost::any_cast<int>(val);}
        if("Y_Smax"==(*_i)->name){Y_Smax = boost::any_cast<int>(val);}
        if("Y_Vmax"==(*_i)->name){Y_Vmax = boost::any_cast<int>(val);}
      }
    }

    int R_Hmin;
int R_Smin;
int R_Vmin;
int R_Hmax;
int R_Smax;
int R_Vmax;
int G_Hmin;
int G_Smin;
int G_Vmin;
int G_Hmax;
int G_Smax;
int G_Vmax;
int B_Hmin;
int B_Smin;
int B_Vmin;
int B_Hmax;
int B_Smax;
int B_Vmax;
int Y_Hmin;
int Y_Smin;
int Y_Vmin;
int Y_Hmax;
int Y_Smax;
int Y_Vmax;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int R_Hmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int R_Smin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int R_Vmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int R_Hmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int R_Smax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int R_Vmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int G_Hmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int G_Smin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int G_Vmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int G_Hmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int G_Smax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int G_Vmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int B_Hmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int B_Smin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int B_Vmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int B_Hmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int B_Smax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int B_Vmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Y_Hmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Y_Smin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Y_Vmin;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Y_Hmax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Y_Smax;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int Y_Vmax;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("ColorHSVConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const ColorHSVConfig &__max__ = __getMax__();
      const ColorHSVConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const ColorHSVConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const ColorHSVConfig &__getDefault__();
    static const ColorHSVConfig &__getMax__();
    static const ColorHSVConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const ColorHSVConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void ColorHSVConfig::ParamDescription<std::string>::clamp(ColorHSVConfig &config, const ColorHSVConfig &max, const ColorHSVConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class ColorHSVConfigStatics
  {
    friend class ColorHSVConfig;

    ColorHSVConfigStatics()
    {
ColorHSVConfig::GroupDescription<ColorHSVConfig::DEFAULT, ColorHSVConfig> Default("Default", "", 0, 0, true, &ColorHSVConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.R_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.R_Hmin = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.R_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::R_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::R_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.R_Smin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.R_Smin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.R_Smin = 85;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::R_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::R_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.R_Vmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.R_Vmin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.R_Vmin = 126;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::R_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::R_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.R_Hmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.R_Hmax = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.R_Hmax = 9;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::R_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::R_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.R_Smax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.R_Smax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.R_Smax = 253;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::R_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::R_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.R_Vmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.R_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.R_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::R_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("R_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::R_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.G_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.G_Hmin = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.G_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::G_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::G_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.G_Smin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.G_Smin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.G_Smin = 85;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::G_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::G_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.G_Vmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.G_Vmin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.G_Vmin = 126;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::G_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::G_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.G_Hmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.G_Hmax = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.G_Hmax = 9;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::G_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::G_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.G_Smax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.G_Smax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.G_Smax = 253;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::G_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::G_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.G_Vmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.G_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.G_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::G_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("G_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::G_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.B_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.B_Hmin = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.B_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::B_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::B_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.B_Smin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.B_Smin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.B_Smin = 85;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::B_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::B_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.B_Vmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.B_Vmin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.B_Vmin = 126;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::B_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::B_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.B_Hmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.B_Hmax = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.B_Hmax = 9;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::B_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::B_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.B_Smax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.B_Smax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.B_Smax = 253;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::B_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::B_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.B_Vmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.B_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.B_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::B_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("B_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::B_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Y_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Y_Hmin = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Y_Hmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::Y_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Hmin", "int", 0, "Hmin in HSV", "", &ColorHSVConfig::Y_Hmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Y_Smin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Y_Smin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Y_Smin = 85;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::Y_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Smin", "int", 0, "Smin in HSV", "", &ColorHSVConfig::Y_Smin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Y_Vmin = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Y_Vmin = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Y_Vmin = 126;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::Y_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Vmin", "int", 0, "Vmin in HSV", "", &ColorHSVConfig::Y_Vmin)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Y_Hmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Y_Hmax = 180;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Y_Hmax = 9;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::Y_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Hmax", "int", 0, "Hmax in HSV", "", &ColorHSVConfig::Y_Hmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Y_Smax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Y_Smax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Y_Smax = 253;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::Y_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Smax", "int", 0, "Smax in HSV", "", &ColorHSVConfig::Y_Smax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Y_Vmax = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Y_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Y_Vmax = 255;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::Y_Vmax)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(ColorHSVConfig::AbstractParamDescriptionConstPtr(new ColorHSVConfig::ParamDescription<int>("Y_Vmax", "int", 0, "Vmax in HSV", "", &ColorHSVConfig::Y_Vmax)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(ColorHSVConfig::AbstractGroupDescriptionConstPtr(new ColorHSVConfig::GroupDescription<ColorHSVConfig::DEFAULT, ColorHSVConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<ColorHSVConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<ColorHSVConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<ColorHSVConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    ColorHSVConfig __max__;
    ColorHSVConfig __min__;
    ColorHSVConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const ColorHSVConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static ColorHSVConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &ColorHSVConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const ColorHSVConfig &ColorHSVConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const ColorHSVConfig &ColorHSVConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const ColorHSVConfig &ColorHSVConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<ColorHSVConfig::AbstractParamDescriptionConstPtr> &ColorHSVConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<ColorHSVConfig::AbstractGroupDescriptionConstPtr> &ColorHSVConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const ColorHSVConfigStatics *ColorHSVConfig::__get_statics__()
  {
    const static ColorHSVConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = ColorHSVConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __COLORHSVRECONFIGURATOR_H__
