// Generated by gencpp from file policies/ActionData.msg
// DO NOT EDIT!


#ifndef POLICIES_MESSAGE_ACTIONDATA_H
#define POLICIES_MESSAGE_ACTIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace policies
{
template <class ContainerAllocator>
struct ActionData_
{
  typedef ActionData_<ContainerAllocator> Type;

  ActionData_()
    : values()  {
    }
  ActionData_(const ContainerAllocator& _alloc)
    : values(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::policies::ActionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::policies::ActionData_<ContainerAllocator> const> ConstPtr;

}; // struct ActionData_

typedef ::policies::ActionData_<std::allocator<void> > ActionData;

typedef boost::shared_ptr< ::policies::ActionData > ActionDataPtr;
typedef boost::shared_ptr< ::policies::ActionData const> ActionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::policies::ActionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::policies::ActionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::policies::ActionData_<ContainerAllocator1> & lhs, const ::policies::ActionData_<ContainerAllocator2> & rhs)
{
  return lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::policies::ActionData_<ContainerAllocator1> & lhs, const ::policies::ActionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace policies

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::policies::ActionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::policies::ActionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::policies::ActionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::policies::ActionData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::policies::ActionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::policies::ActionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::policies::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c9c4a808bfa8ef83980bb0222137bf";
  }

  static const char* value(const ::policies::ActionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c9c4a808bfa8efULL;
  static const uint64_t static_value2 = 0x83980bb0222137bfULL;
};

template<class ContainerAllocator>
struct DataType< ::policies::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "policies/ActionData";
  }

  static const char* value(const ::policies::ActionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::policies::ActionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] values\n"
;
  }

  static const char* value(const ::policies::ActionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::policies::ActionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::policies::ActionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::policies::ActionData_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLICIES_MESSAGE_ACTIONDATA_H
