// Generated by gencpp from file policies/ObservationData.msg
// DO NOT EDIT!


#ifndef POLICIES_MESSAGE_OBSERVATIONDATA_H
#define POLICIES_MESSAGE_OBSERVATIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <policies/SegmentationData.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/Image.h>

namespace policies
{
template <class ContainerAllocator>
struct ObservationData_
{
  typedef ObservationData_<ContainerAllocator> Type;

  ObservationData_()
    : segmentation_data()
    , color_image()
    , depth_image()
    , target_image()  {
    }
  ObservationData_(const ContainerAllocator& _alloc)
    : segmentation_data(_alloc)
    , color_image(_alloc)
    , depth_image(_alloc)
    , target_image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::policies::SegmentationData_<ContainerAllocator>  _segmentation_data_type;
  _segmentation_data_type segmentation_data;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _color_image_type;
  _color_image_type color_image;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_image_type;
  _depth_image_type depth_image;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _target_image_type;
  _target_image_type target_image;





  typedef boost::shared_ptr< ::policies::ObservationData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::policies::ObservationData_<ContainerAllocator> const> ConstPtr;

}; // struct ObservationData_

typedef ::policies::ObservationData_<std::allocator<void> > ObservationData;

typedef boost::shared_ptr< ::policies::ObservationData > ObservationDataPtr;
typedef boost::shared_ptr< ::policies::ObservationData const> ObservationDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::policies::ObservationData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::policies::ObservationData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::policies::ObservationData_<ContainerAllocator1> & lhs, const ::policies::ObservationData_<ContainerAllocator2> & rhs)
{
  return lhs.segmentation_data == rhs.segmentation_data &&
    lhs.color_image == rhs.color_image &&
    lhs.depth_image == rhs.depth_image &&
    lhs.target_image == rhs.target_image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::policies::ObservationData_<ContainerAllocator1> & lhs, const ::policies::ObservationData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace policies

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::policies::ObservationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::policies::ObservationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::policies::ObservationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::policies::ObservationData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::policies::ObservationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::policies::ObservationData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::policies::ObservationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "668d9532d885ccea48d54a733ff76583";
  }

  static const char* value(const ::policies::ObservationData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x668d9532d885cceaULL;
  static const uint64_t static_value2 = 0x48d54a733ff76583ULL;
};

template<class ContainerAllocator>
struct DataType< ::policies::ObservationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "policies/ObservationData";
  }

  static const char* value(const ::policies::ObservationData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::policies::ObservationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SegmentationData segmentation_data\n"
"sensor_msgs/Image color_image\n"
"sensor_msgs/Image depth_image\n"
"sensor_msgs/Image target_image\n"
"================================================================================\n"
"MSG: policies/SegmentationData\n"
"Header header\n"
"sensor_msgs/Image pred_mask\n"
"sensor_msgs/Image[] raw_masks\n"
"sensor_msgs/Image[] processed_masks\n"
"int32[] bbox_x1\n"
"int32[] bbox_y1\n"
"int32[] bbox_x2\n"
"int32[] bbox_y2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::policies::ObservationData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::policies::ObservationData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.segmentation_data);
      stream.next(m.color_image);
      stream.next(m.depth_image);
      stream.next(m.target_image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObservationData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::policies::ObservationData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::policies::ObservationData_<ContainerAllocator>& v)
  {
    s << indent << "segmentation_data: ";
    s << std::endl;
    Printer< ::policies::SegmentationData_<ContainerAllocator> >::stream(s, indent + "  ", v.segmentation_data);
    s << indent << "color_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.color_image);
    s << indent << "depth_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth_image);
    s << indent << "target_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.target_image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLICIES_MESSAGE_OBSERVATIONDATA_H
