// Generated by gencpp from file policies/SegmentationData.msg
// DO NOT EDIT!


#ifndef POLICIES_MESSAGE_SEGMENTATIONDATA_H
#define POLICIES_MESSAGE_SEGMENTATIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <policies/Image_Msg.h>
#include <policies/Image_Msg.h>
#include <policies/Image_Msg.h>

namespace policies
{
template <class ContainerAllocator>
struct SegmentationData_
{
  typedef SegmentationData_<ContainerAllocator> Type;

  SegmentationData_()
    : header()
    , pred_mask()
    , raw_masks()
    , processed_masks()
    , bbox_x1()
    , bbox_y1()
    , bbox_x2()
    , bbox_y2()  {
    }
  SegmentationData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pred_mask(_alloc)
    , raw_masks(_alloc)
    , processed_masks(_alloc)
    , bbox_x1(_alloc)
    , bbox_y1(_alloc)
    , bbox_x2(_alloc)
    , bbox_y2(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::policies::Image_Msg_<ContainerAllocator>  _pred_mask_type;
  _pred_mask_type pred_mask;

   typedef std::vector< ::policies::Image_Msg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::policies::Image_Msg_<ContainerAllocator> >> _raw_masks_type;
  _raw_masks_type raw_masks;

   typedef std::vector< ::policies::Image_Msg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::policies::Image_Msg_<ContainerAllocator> >> _processed_masks_type;
  _processed_masks_type processed_masks;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _bbox_x1_type;
  _bbox_x1_type bbox_x1;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _bbox_y1_type;
  _bbox_y1_type bbox_y1;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _bbox_x2_type;
  _bbox_x2_type bbox_x2;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _bbox_y2_type;
  _bbox_y2_type bbox_y2;





  typedef boost::shared_ptr< ::policies::SegmentationData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::policies::SegmentationData_<ContainerAllocator> const> ConstPtr;

}; // struct SegmentationData_

typedef ::policies::SegmentationData_<std::allocator<void> > SegmentationData;

typedef boost::shared_ptr< ::policies::SegmentationData > SegmentationDataPtr;
typedef boost::shared_ptr< ::policies::SegmentationData const> SegmentationDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::policies::SegmentationData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::policies::SegmentationData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::policies::SegmentationData_<ContainerAllocator1> & lhs, const ::policies::SegmentationData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pred_mask == rhs.pred_mask &&
    lhs.raw_masks == rhs.raw_masks &&
    lhs.processed_masks == rhs.processed_masks &&
    lhs.bbox_x1 == rhs.bbox_x1 &&
    lhs.bbox_y1 == rhs.bbox_y1 &&
    lhs.bbox_x2 == rhs.bbox_x2 &&
    lhs.bbox_y2 == rhs.bbox_y2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::policies::SegmentationData_<ContainerAllocator1> & lhs, const ::policies::SegmentationData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace policies

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::policies::SegmentationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::policies::SegmentationData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::policies::SegmentationData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::policies::SegmentationData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::policies::SegmentationData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::policies::SegmentationData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::policies::SegmentationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df055109b3a4d4227a16413106365ed9";
  }

  static const char* value(const ::policies::SegmentationData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf055109b3a4d422ULL;
  static const uint64_t static_value2 = 0x7a16413106365ed9ULL;
};

template<class ContainerAllocator>
struct DataType< ::policies::SegmentationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "policies/SegmentationData";
  }

  static const char* value(const ::policies::SegmentationData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::policies::SegmentationData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Image_Msg pred_mask\n"
"Image_Msg[] raw_masks\n"
"Image_Msg[] processed_masks\n"
"int32[] bbox_x1\n"
"int32[] bbox_y1\n"
"int32[] bbox_x2\n"
"int32[] bbox_y2\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: policies/Image_Msg\n"
"int32 height\n"
"int32 width\n"
"int32 channels\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::policies::SegmentationData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::policies::SegmentationData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pred_mask);
      stream.next(m.raw_masks);
      stream.next(m.processed_masks);
      stream.next(m.bbox_x1);
      stream.next(m.bbox_y1);
      stream.next(m.bbox_x2);
      stream.next(m.bbox_y2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SegmentationData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::policies::SegmentationData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::policies::SegmentationData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pred_mask: ";
    s << std::endl;
    Printer< ::policies::Image_Msg_<ContainerAllocator> >::stream(s, indent + "  ", v.pred_mask);
    s << indent << "raw_masks[]" << std::endl;
    for (size_t i = 0; i < v.raw_masks.size(); ++i)
    {
      s << indent << "  raw_masks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::policies::Image_Msg_<ContainerAllocator> >::stream(s, indent + "    ", v.raw_masks[i]);
    }
    s << indent << "processed_masks[]" << std::endl;
    for (size_t i = 0; i < v.processed_masks.size(); ++i)
    {
      s << indent << "  processed_masks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::policies::Image_Msg_<ContainerAllocator> >::stream(s, indent + "    ", v.processed_masks[i]);
    }
    s << indent << "bbox_x1[]" << std::endl;
    for (size_t i = 0; i < v.bbox_x1.size(); ++i)
    {
      s << indent << "  bbox_x1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bbox_x1[i]);
    }
    s << indent << "bbox_y1[]" << std::endl;
    for (size_t i = 0; i < v.bbox_y1.size(); ++i)
    {
      s << indent << "  bbox_y1[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bbox_y1[i]);
    }
    s << indent << "bbox_x2[]" << std::endl;
    for (size_t i = 0; i < v.bbox_x2.size(); ++i)
    {
      s << indent << "  bbox_x2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bbox_x2[i]);
    }
    s << indent << "bbox_y2[]" << std::endl;
    for (size_t i = 0; i < v.bbox_y2.size(); ++i)
    {
      s << indent << "  bbox_y2[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.bbox_y2[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLICIES_MESSAGE_SEGMENTATIONDATA_H
