# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: grip_group
  joint_model_group_pose: close
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Arm1_Joint
    - Arm2_Joint
    - Arm3_Joint
    - Arm4_Joint
    - Arm5_Joint
    - grip_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Arm1_Joint
    - Arm2_Joint
    - Arm3_Joint
    - Arm4_Joint
    - Arm5_Joint
  gains:
    Arm1_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm2_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm3_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm4_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm5_Joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1