// Generated by gencpp from file dofbot_pro_info/dofbot_pro_kinemarics.msg
// DO NOT EDIT!


#ifndef dofbot_pro_info_MESSAGE_DOFBOT_PRO_KINEMARICS_H
#define dofbot_pro_info_MESSAGE_DOFBOT_PRO_KINEMARICS_H

#include <ros/service_traits.h>


#include <dofbot_pro_info/dofbot_pro_kinemaricsRequest.h>
#include <dofbot_pro_info/dofbot_pro_kinemaricsResponse.h>


namespace dofbot_pro_info
{

struct dofbot_pro_kinemarics
{

typedef dofbot_pro_kinemaricsRequest Request;
typedef dofbot_pro_kinemaricsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct dofbot_pro_kinemarics
} // namespace dofbot_pro_info


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemarics > {
  static const char* value()
  {
    return "d4d7066ccc45dfff67e7b0b528d14e9b";
  }

  static const char* value(const ::dofbot_pro_info::dofbot_pro_kinemarics&) { return value(); }
};

template<>
struct DataType< ::dofbot_pro_info::dofbot_pro_kinemarics > {
  static const char* value()
  {
    return "dofbot_pro_info/dofbot_pro_kinemarics";
  }

  static const char* value(const ::dofbot_pro_info::dofbot_pro_kinemarics&) { return value(); }
};


// service_traits::MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemaricsRequest> should match
// service_traits::MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemarics >
template<>
struct MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemaricsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemarics >::value();
  }
  static const char* value(const ::dofbot_pro_info::dofbot_pro_kinemaricsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dofbot_pro_info::dofbot_pro_kinemaricsRequest> should match
// service_traits::DataType< ::dofbot_pro_info::dofbot_pro_kinemarics >
template<>
struct DataType< ::dofbot_pro_info::dofbot_pro_kinemaricsRequest>
{
  static const char* value()
  {
    return DataType< ::dofbot_pro_info::dofbot_pro_kinemarics >::value();
  }
  static const char* value(const ::dofbot_pro_info::dofbot_pro_kinemaricsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemaricsResponse> should match
// service_traits::MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemarics >
template<>
struct MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemaricsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dofbot_pro_info::dofbot_pro_kinemarics >::value();
  }
  static const char* value(const ::dofbot_pro_info::dofbot_pro_kinemaricsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dofbot_pro_info::dofbot_pro_kinemaricsResponse> should match
// service_traits::DataType< ::dofbot_pro_info::dofbot_pro_kinemarics >
template<>
struct DataType< ::dofbot_pro_info::dofbot_pro_kinemaricsResponse>
{
  static const char* value()
  {
    return DataType< ::dofbot_pro_info::dofbot_pro_kinemarics >::value();
  }
  static const char* value(const ::dofbot_pro_info::dofbot_pro_kinemaricsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // dofbot_pro_info_MESSAGE_DOFBOT_PRO_KINEMARICS_H
