# AprilTag 3 code parameters
# Find descriptions in apriltag/include/apriltag.h:struct apriltag_detector
#                      apriltag/include/apriltag.h:struct apriltag_family
tag_family:        'tag36h11' # options: tagStandard52h13, tagStandard41h12, tag36h11, tag25h9, tag16h5, tagCustom48h12, tagCircle21h7, tagCircle49h12
tag_threads:       2          # default: 2     
tag_decimate:      1.0        # default: 1.0   # 减小图像分辨率
tag_blur:          0.0        # default: 0.0   # 设置tag_blur> 0模糊图像，tag_blur  < 0锐化图像
tag_refine_edges:  1          # default: 1     # 增强了计算精度，但消耗了算力
tag_debug:         0          # default: 0     # 1为保存中间图像到~/.ros
max_hamming_dist:  2          # default: 2 (Tunable parameter with 2 being a good choice - values >=3 consume large amounts of memory. Choose the largest value possible.)
# Other parameters
publish_tf:        true       # default: false  # 发布tf坐标
transport_hint:    "raw"      # default: raw, see http://wiki.ros.org/image_transport#Known_Transport_Packages for options
